### ISSUE TITLE
hasOwnProperty

### ISSUE THREAD

**Issue by thatjessicakelly** [sindresorhus/dot-prop#23] opened 2016-03-02 05:39 UTC
Right now dot-prop will return any property that isn't `undefined`. But as a potentially unintended consequence stuff like `m.get({}, 'hasOwnProperty')` will return the non-enumerable method.

Instead of checking just for `undefined`, maybe it should test `obj.hasOwnProperty(prop)`.

**Comment by sindresorhus** [comment] 2016-03-02 08:02
I think that's intentional. If we used `hasOwnProperty` it would not work on inherited properties.

> m.get({}, 'hasOwnProperty') will return the non-enumerable method.

But so will `({}).hasOwnProperty`. This module is meant to imitate normal object handling.

**Comment by thatjessicakelly** [comment] 2016-03-02 09:23
>  This module is meant to imitate normal object handling.

It doesn't really do that though, `undefined` is special cased. If you run `({ foo: undefined }).foo.bar` you will get a `TypeError`, where this module will return `undefined`. But at the same time `({ foo: null }).foo.bar` will throw a `TypeError` in both cases.

I'm not saying that `get({ foo: undefined }, 'foo.bar')` should throw– it's clearly more useful that it doesn't.

I just think that it's more useful if `get({ foo: null }, 'foo.bar')` does not throw and `get({}, 'hasOwnProperty')` returns `undefined`.

**Comment by sindresorhus** [comment] 2016-03-02 09:32
> I just think that it's more useful if get({ foo: null }, 'foo.bar') does not throw and get({}, 'hasOwnProperty') returns undefined.

Yes. I definitely agree with that.

**Comment by stevemao** [comment] 2016-03-02 09:33
duplicate of #11?

**Comment by stevemao** [comment] 2016-03-02 09:34
@sindresorhus Do you want to ignore inherited properties?

**Comment by sindresorhus** [comment] 2016-03-02 09:35
No

**Comment by stevemao** [comment] 2016-03-02 09:39
> get({}, 'hasOwnProperty') returns undefined.

isn't `hasOwnProperty` a property of `Object.prototype`?

**Comment by sindresorhus** [comment] 2016-03-02 09:52
Yes, but it's `enumerable: false`:

```js
Object.getOwnPropertyDescriptor(Object.prototype, 'hasOwnProperty');
/*
{
  "writable": true,
  "enumerable": false,
  "configurable": true
}
*/
```

**Comment by stevemao** [comment] 2016-03-02 10:06
Hmm.. I'm just trying to understand this. I'm not enumerating the properties of an object.. I'm just trying to access it.

**Comment by SamVerschueren** [comment] 2016-03-27 14:02
@stevemao I think what Sindre is trying to say here is that if the descriptor tells us that it is not `enumerable`, it shouldn't be accessed and thus should be ignored. So inherited properties shouldn't be ignored, only non-enumerable properties.

**Comment by stevemao** [comment] 2016-03-29 11:38
> if the descriptor tells us that it is not enumerable, it shouldn't be accessed and thus should be ignored.

@SamVerschueren, I just think that enumerability should have nothing to do with accessibility...

**Closed** 2016-05-18 05:57 UTC
Labels: enhancement, help wanted
